### ISSUE TITLE
Is it still alive?

### ISSUE THREAD

**Issue by szaghi** [maxlevesque/multigrid-lib#1]
@maxlevesque This project is very interesting for me, in the next feature I planned to develop a KISS Fortran library (OOP) for multigrid schemes (I am mainly interested into CFD). However, your project seems to be no longer mainteneid/started. Is it still alive? Are You still interested on it? Maybe we can co-work on it. 

I am a member of the https://github.com/Fortran-FOSS-Programmers where we are developing FOSS Fortran codes, maybe you are interested to join us.

Thank you for sharing your work.

My best regards,

Stefano

**Comment by maxlevesque** [comment]
Hi @szaghi,
I wrote a small library, but then stopped reinventing the wheel when I discovered [TRILINOS/MUELU](https://trilinos.org/packages/muelu/).

So, to answer your question: No, this lib is not developped anymore.
For what refers to your second question, I'd be happy to have a look at your FOSS stuff :).

I'll remove this repo. Thanks.
